// All portfolio items for related works
export const allPortfolioItems = [
    {
        id: "5",
        title: "Orange December - Travel Website",
        category: "Web Design",
        completionTime: "5 WEEKS",
        feeCharged: "₵3K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/web-3.png-dsVwLIMJHEDLUTurrGFTLb6EPIxCXI.jpeg",
        slug: "orange-december",
        client: "Bonvas Tours",
        year: "2024"
    },
    {
        id: "w3",
        title: "Enfoni - Graduation Photography Services",
        category: "Web Design",
        completionTime: "3 WEEKS",
        feeCharged: "₵1.5K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-enfoni-ruby-vercel-app-2025-05-04-15_54_50-sozU1SCmd7FLV2MoWIMEWRX2I7bKx2.png",
        slug: "enfoni",
        client: "Enfoni",
    },
    {
        id: "w4",
        title: "Pizza Man Chicken Man - Restaurant Website",
        category: "Web Design",
        completionTime: "4 WEEKS",
        feeCharged: "₵3K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-pizzamanchickenman-2025-05-04-15_03_00-r47KQFQVayn0Yo3cNFfGUksi7iOR0S.png",
        slug: "pizza-man",
        client: "Pizza Man Chicken Man",
    },
    {
        id: "w7",
        title: "Lynx Studios - Photography & Design Portfolio",
        category: "Web Design",
        completionTime: "4 WEEKS",
        feeCharged: "₵1.6K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/FireShot%20Capture%20007%20-%20Lynx%20Studios%20-%20%5B%5D-GcDBmRl4fbnGZKxox7psLsrpn0fb9c.png",
        slug: "lynx-studios",
        client: "Lynx Studios",
    },
    {
        id: "6",
        title: "Bonvas Tours - Travel Agency Website",
        category: "Web Design",
        completionTime: "7 WEEKS",
        feeCharged: "₵10K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/web-1.png-nKEPt61O1a1kKHtq4gvh6lrdtGkkCX.jpeg",
        slug: "bonvas-tours",
        client: "Bonvas Tours",
        year: "2025"
    },
    {
        id: "w5",
        title: "Specks Kitchen - Bakery & Pastry Shop",
        category: "Web Design",
        completionTime: "3 WEEKS",
        feeCharged: "₵1.4K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-specks-kitchen-vercel-app-2025-05-04-15_32_26-DjAB8rWZfOMQZQ2E6G0sJCV8K7wQA2.png",
        slug: "specks-kitchen",
        client: "Specks Kitchen",
    },
    {
        id: "w6",
        title: "E-Procurepro - Procurement Solutions",
        category: "Web Design",
        completionTime: "5 WEEKS",
        feeCharged: "₵2.2K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-e-procurement-landing-page-vercel-app-2025-05-04-15_01_32-FFvSWVnRI33jc04fqgi4t7R0PONi1e.png",
        slug: "e-procurepro",
        client: "E-Procurepro",
    },
   
    {
        id: "4",
        title: "Hala-Gh Mobile Payment Platform",
        category: "UI Design",
        completionTime: "6 WEEKS",
        feeCharged: "₵18K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ui-1-1C4GdzvprHbCNLutSyGEDkxwkWd0sw.png",
        slug: "hala-gh",
        client: "Hala-Gh",
        year: "2023"
    },
    {
        id: "9",
        title: "Bonvas Tours Adventure Packages",
        category: "Web Design",
        completionTime: "6 WEEKS",
        feeCharged: "₵3K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/web-5-S6d1TrEKClzWCAzmwO7NjzmCOSFce8.png",
        slug: "bonvas-adventure",
        client: "Bonvas Tours",
        year: "2024"
    },
    {
        id: "w1",
        title: "DE Bookkeepers - Accounting & Tax Services",
        category: "Web Design",
        completionTime: "4 WEEKS",
        feeCharged: "₵1.2K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-localhost-debookkepers-2025-05-04-16_00_35-CaSBfGN9BgdhCB8IBATAeLUXZ9AV0o.png",
        slug: "de-bookkeepers",
        client: "DE Bookkeepers",
    },
    {
        id: "w2",
        title: "Microbit Systems Limited - Cybersecurity Solutions",
        category: "Web Design",
        completionTime: "6 WEEKS",
        feeCharged: "₵2.5K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screencapture-msl-silk-vercel-app-2025-05-04-15_56_26-FgcEO8aQQOya9XYCq8rqekLxOn825v.png",
        slug: "microbit-systems",
        client: "Microbit Systems Limited",
    },
    {
        id: "10",
        title: "African Cancer Coalition Meeting",
        category: "Web Design",
        completionTime: "4 WEEKS",
        feeCharged: "₵3K",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/web-4-RQRs8JxRY5J9AaSlpJzCb7HeBoBElO.png",
        slug: "cancer-coalition",
        client: "African Cancer Coalition",
        year: "2024"
    },

    {
        id: "g1",
        title: "Cereal Queen - Food Product Branding",
        category: "Graphic Design",
        completionTime: "2 Days",
        feeCharged: "₵150",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cereal%20Queen%20Flyer.jpg-UYujMYZnUZ2H32r1YBZVLfzaHiGkxe.jpeg",
        slug: "cereal-queen",
        client: "Cereal Queen",
    },
    {
        id: "g2",
        title: "Janeluv Bakes - Online Course Advertisement",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵200",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Online_Course-9Cszde3aMZNWhoN2jkDRn4UNHzjMwY.png",
        slug: "janeluv-bakes",
        client: "Janeluv Bakes",
    },
    {
        id: "g3",
        title: "Kuulchat - Educational Technology Billboard",
        category: "Graphic Design",
        completionTime: "2 DAYS",
        feeCharged: "₵100",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kuulchat%20Billboard.jpg-dwR2dJgmgy63gW7sYXD7rMitfpCRG0.jpeg",
        slug: "kuulchat-billboard",
        client: "Kuulchat",
    },
    {
        id: "g4",
        title: "Lionage Clinic-GH - Medical Services Flyer",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵200",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lionage-Clinic-GH.jpg-5FoVVM9BEOeHD2ZfGEsgPHjwGtXaeP.jpeg",
        slug: "lionage-clinic",
        client: "Lionage Clinic-GH",
    },
    {
        id: "g5",
        title: "Ray Accessories - Product Advertisement",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵100",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ray%20Accessories.jpg-3CjsPqBNNsdXy9MPSVM12IQNLgJ1lt.jpeg",
        slug: "ray-accessories",
        client: "Ray Accessories",
    },
    {
        id: "g6",
        title: "ToddlerWalks - Educational Platform Promotion",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵200",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/A5%20Pull%20Up%20version.jpg-6xRk6X8YrmgkTMGGCZsk9b1mAPNZy0.jpeg",
        slug: "toddlerwalks",
        client: "ToddlerWalks",
    },
    {
        id: "g7",
        title: "Exam Wishes - Student Support Flyer",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵100",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Midsem%20Exam%20Wish%20Flyer.jpg-KtRsPrRdNQQddb9J66d6bx5jxd6OQo.jpeg",
        slug: "exam-wishes",
        client: "ToddlerWalks",
    },
    {
        id: "g8",
        title: "ACES - Association Membership Badge",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵100",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/aces%20sticker.jpg-lR1GfeFrZoL70FtUj7frZrtWp1Lp92.jpeg",
        slug: "aces-badge",
        client: "KNUST ACES",
    },
    {
        id: "g9",
        title: "NSBE - End of Semester Support Flyer",
        category: "Graphic Design",
        completionTime: "1 DAYS",
        feeCharged: "₵100",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/End%20of%20semester%20flyer.jpg-o3vPQ32mwaFJfPLjt1nJ1ry72PaUVn.jpeg",
        slug: "nsbe-flyer",
        client: "KNUST NSBE",
    },
    {
        id: "g10",
        title: "Detective Ent - Cryptocurrency Trading Ad",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵150",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Detective%20Ent%20Flyer2.jpg-NwDrZRPwNEqvGMB52iFLe55PqSNHBV.jpeg",
        slug: "detective-ent",
        client: "Detective Ent",
    },
    {
        id: "g11",
        title: "Homadel Transport - Logistics Company Branding",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Homadi%20Transport-HTXdY0Yte1cifp21qCYu6djYF1KrsB.png",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵100",
        slug: "homadel-transport",
        client: "Homadel Enterprise",
    },
    {
        id: "g12",
        title: "Nimo Johnson - Music Ministry T-Shirt Design",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Nimo%20music%20T-Shirt2.jpg-8KI9tQpqkuEjmFyfKVSUNahKxgkK3P.jpeg",
        category: "Graphic Design",
        completionTime: "2 DAYS",
        feeCharged: "₵300",
        slug: "nimo-music-tshirt",
        client: "Nimo Johnson Music Ministry",
    },
    {
        id: "g13",
        title: "Love Yourself - Motivational Social Media Post",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/qoute48.jpg-iZ7DtKza608HggGcY8ScyzZW2mk2lU.jpeg",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵50",
        slug: "love-yourself-quote",
        client: "Scholar Studio",
    },
    {
        id: "g14",
        title: "ACES - Thank You Election Campaign Flyer",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Thanks%20flyer2.jpg-HpQQYf3AXy4eyRKYRDwbIoABZSMvaq.jpeg",
        category: "Graphic Design",
        completionTime: "2 DAYS",
        feeCharged: "₵120",
        slug: "aces-thank-you",
        client: "KNUST ACES",
    },
    {
        id: "g15",
        title: "NSBE - 25th Anniversary Celebration Flyer",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Anniversary%20Celebration.jpg-nZ83uy9qRm4r7YuOFo2bft3EyPiEXh.jpeg",
        category: "Graphic Design",
        completionTime: "2 DAYS",
        feeCharged: "₵200",
        slug: "nsbe-anniversary",
        client: "KNUST NSBE",
    },
    {
        id: "g16",
        title: "FTA Fund - Investment Promotion Design",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/FTA_F1-3RiCiJQxAN6bCSdbivLSaSn7Iz8KGN.png",
        category: "Graphic Design",
        completionTime: "1 DAYS",
        feeCharged: "₵150",
        slug: "fta-fund",
        client: "FTA Fund",
    },
    {
        id: "g17",
        title: "Build Your Dreams - Motivational Quote Design",
        image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/qoute22.jpg-cEhbyqJakA77AqRcLzRE5uOCNfurRL.jpeg",
        category: "Graphic Design",
        completionTime: "1 DAY",
        feeCharged: "₵50",
        slug: "build-dreams-quote",
        client: "Scholar Studio",
    },
    {
        id: "g18",
        title: "IOT Campus Africa - Recruitment Flyer",
        image:
            "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/RECRUITMENT%20Flyer.jpg-giv83u6mZeKzF3GR8FFKVp5IRJ8w3y.jpeg",
        category: "Graphic Design",
        completionTime: "1 DAYS",
        feeCharged: "₵150",
        slug: "iot-recruitment",
        client: "KNUST IOT Campus Africa",
    },
]