// Pricing data
export const pricingData = {
  fullstack: {
    title: "Full-Stack Digital Solutions",
    description: "Comprehensive digital experiences spanning mobile, web, and responsive design.",
    plans: [
      {
        id: "fullstack-basic",
        name: "Basic",
        price: "₵3,000",
        description: "Essential web presence for small businesses",
        features: [
          "Responsive website (up to 2 pages)",
          "Mobile-friendly design",
          "Contact form integration",
          "Social media integration",
          "Basic SEO setup",
          "1 month support",
          "Content Management System",
          "Performance optimization",
          "API development & integrations",
        ],
        included: [true, true, true, true, true, true, false, false, false, false, false, false],
        note: "Hosting and domain not included",
      },
      {
        id: "fullstack-standard",
        name: "Standard",
        price: "₵20,000",
        description: "Comprehensive solution for growing businesses",
        features: [
          "Responsive website (up to 10 pages)",
          "Mobile-friendly design",
          "Contact form integration",
          "Social media integration",
          "Advanced SEO optimization",
          "3 months support",
          "Content Management System",
          "E-commerce functionality (up to 20 products)",
          "Performance optimization",
          "API development & integrations",
          "Extended support period",
        ],
        included: [true, true, true, true, true, true, true, true, true, false, false, false],
        note: "Hosting and domain not included",
        popular: true,
      },
      {
        id: "fullstack-premium",
        name: "Premium",
        price: "₵25,000+",
        description: "Advanced solutions for established businesses",
        features: [
          "Custom web application",
          "Mobile-friendly design",
          "Contact form integration",
          "Social media integration",
          "Advanced SEO optimization",
          "6 months support",
          "Content Management System",
          "Full e-commerce functionality",
          "Performance optimization",
          "API development & integrations",
          "User authentication system",
          "Extended support period",
        ],
        included: [true, true, true, true, true, true, true, true, true, true, true, true],
        note: "Custom quote based on requirements",
      },
    ],
  },
  uiux: {
    title: "UI/UX Design",
    description: "Purposeful interfaces that marry aesthetic sophistication with behavioral psychology.",
    plans: [
      {
        id: "uiux-basic",
        name: "Basic",
        price: "₵3,000",
        description: "Essential design for new products",
        features: [
          "UI audit & recommendations",
          "Design for 4 key flows",
          "Basic style guide",
          "Responsive considerations",
          "Source files included",
          "1 revision round",
          "User research & personas",
          "Information architecture",
          "Wireframing & prototyping",
          "Interactive prototype",
          "Component library",
          "Animation specifications",
        ],
        included: [true, true, true, true, true, true, false, false, false, false, false, false],
        note: "Implementation available separately",
      },
      {
        id: "uiux-standard",
        name: "Standard",
        price: "₵10,000",
        description: "Comprehensive design with user experience focus",
        features: [
          "UI audit & recommendations",
          "Design for 10 flows",
          "Extended style guide",
          "Responsive considerations",
          "Source files included",
          "2 revision rounds",
          "User research & personas",
          "Information architecture",
          "Wireframing & prototyping",
          "Interactive prototype",
          "Component library",
          "Animation specifications",
        ],
        included: [true, true, true, true, true, true, true, true, true, true, false, false],
        note: "Implementation available separately",
        popular: true,
      },
      {
        id: "uiux-premium",
        name: "Premium",
        price: "₵15,000+",
        description: "Enterprise-grade design system",
        features: [
          "UI audit & recommendations",
          "Design for unlimited screens",
          "Comprehensive style guide",
          "Responsive considerations",
          "Source files included",
          "3 revision rounds",
          "Comprehensive user research",
          "Information architecture",
          "Wireframing & prototyping",
          "Interactive prototype",
          "Complete component library",
          "Animation specifications",
        ],
        included: [true, true, true, true, true, true, true, true, true, true, true, true],
        note: "Custom quote based on complexity",
      },
    ],
  },
  graphic: {
    title: "Graphic Design",
    description: "Distinctive brand ecosystems with unified design language across all touchpoints.",
    plans: [
      {
        id: "graphic-basic",
        name: "Basic",
        price: "₵1,000",
        description: "Essential branding for new businesses",
        features: [
          "Logo design (2 concepts)",
          "Basic color palette",
          "Typography selection",
          "Business card design",
          "Social media profiles",
          "1 revision round",
          "Extended color system",
          "Brand guidelines",
          "Marketing collateral",
          "Custom iconography",
          "Pattern development",
          "Photography style guide",
        ],
        included: [true, true, true, true, true, true, false, false, false, false, false, false],
        note: "Additional materials available separately",
      },
      {
        id: "graphic-standard",
        name: "Standard",
        price: "₵1,500",
        description: "Comprehensive branding for growing businesses",
        features: [
          "Logo with variations",
          "Extended color system",
          "Typography hierarchy",
          "Business stationery set",
          "Social media kit",
          "2 revision rounds",
          "Basic brand guidelines",
          "Marketing collateral (3 items)",
          "Email signature design",
          "Custom iconography",
          "Pattern development",
          "Photography style guide",
        ],
        included: [true, true, true, true, true, true, true, true, true, false, false, false],
        note: "Additional materials available separately",
        popular: true,
      },
      {
        id: "graphic-premium",
        name: "Premium",
        price: "₵2,000+",
        description: "Complete brand system for established businesses",
        features: [
          "Full logo system",
          "Comprehensive color system",
          "Complete typography hierarchy",
          "Business stationery set",
          "Social media kit",
          "3 revision rounds",
          "Comprehensive brand guidelines",
          "Marketing collateral (5+ items)",
          "Email signature design",
          "Custom iconography",
          "Pattern & texture development",
          "Photography style guide",
        ],
        included: [true, true, true, true, true, true, true, true, true, true, true, true],
        note: "Custom quote based on requirements",
      },
    ],
  },
}
